### ISSUE TITLE
Warning message pop-up.

### ISSUE THREAD

**Issue by andytang2008** [NYULibraries/eluna-2019-devday-advanced-workshop#3]
When running docker-compose build, there are some warning message out. We use Centos 7.6.

yarn install v1.15.2
**warning package.json: No license field**
**warning primo-explore-devenv@1.0.5: No license field**
[1/5] Validating package.json...
**warning primo-explore-devenv@1.0.5: No license field**
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.1.3: **The platform "linux" is incompatible with this module.**
**info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.**
[4/5] Linking dependencies...
[5/5] Building fresh packages...

**Comment by etgrieco** [comment]
@andytang2008 yep, that's fine. Thanks for the heads up! That's a predictable warning, but still should return a code 0. Did the package work still?

Those warning messages are coming from the Docker image's linux. It's an optional dependency (of another dependency) and doesn't affect functionality.

**Comment by andytang2008** [comment]
Elliott,

It works pretty well.

Thank you very much.
