### ISSUE TITLE
Some error about git check out.

### ISSUE THREAD

**Issue by andytang2008** [NYULibraries/eluna-2019-devday-advanced-workshop#4]
When running the command "git checkout" command below, some error message is out.
    **git checkout part-2-modularize-and-unit-test
     error: pathspec 'part-2-modularize-and-unit-test' did not match any file(s) known to git.**

Try to use 
     **git fetch
     git checkout -b part-2-modularize-and-unit-test**
Then, it displayed as below.
     **Switched to a new branch 'part-2-modularize-and-unit-test'**

Then,  it is successful to run the command below.
     **git merge upstream/part-2-modularize-and-unit-test**
We don't know whether it is appropriate to do like this.

BTW: it seems that there is some typo error in below command.
**git merge upstream/part-4-circle-ci**

We use "**git merge upstream/part-4-circleci**", however, it has some mistake as below.
error: 'merge' is not possible because you have unmerged files.
hint: Fix them up in the work tree,
hint: and then use 'git add/rm <file>' as
hint: appropriate to mark resolution and make a commit,
hint: or use 'git commit -a'.
fatal: Exiting because of an unresolved conflict.

Any help would be appreciated.

**Comment by etgrieco** [comment]
@andytang2008 if you forked recently (in past 48 hours) there shouldn't be any major changes to worry about. I'm taking a look at your fork and it looks like you're in sync with the current state of the repository and can skip these steps. 

The problem you may be running into is that there is either some changes that need to be committed/discarded, or, you need to simply create the *part-* branches by checking out from origin and making the branch yourself.

git checkout origin/part-... to get it from remote
git checkout -b part-...to create a local version of it

**Comment by andytang2008** [comment]
Thank you so much.
